#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEY → arquivo gravados nesta execução
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  # terminais do Windows (Git Bash) colam com marcas invisíveis "ESC[200~ … ESC[201~"; chaves não têm espaço
  input="${input//$'\e[200~'/}"; input="${input//$'\e[201~'/}"; input="${input//[$'\r\n\t ']/}"
  # console do Windows: Ctrl+V não cola, só manda um caractere de controle. Nesse caso, lê a área de transferência.
  if [[ -n "$input" && -z "${input//[[:cntrl:]]/}" ]]; then
    input=$( (cat /dev/clipboard 2>/dev/null || powershell.exe -NoProfile -Command Get-Clipboard 2>/dev/null) | tr -d '\r\n\t ')
    [[ -n "$input" ]] && printf '  %s(lido da área de transferência)%s\n' "$DIM" "$RESET"
  fi
  input="${input//[[:cntrl:]]/}"
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key → $ENV_FILE")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "gravado: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}


# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────
#
# Assistente do Presente: tarefas que só uma pessoa com acesso às contas pode fazer.
#
#   npm run assistente -- chave       troca a chave secreta do Supabase
#   npm run assistente -- turnstile   ativa a verificação "não sou robô"
#   npm run assistente -- equipe      dá acesso a uma nova pessoa da Equipe
#   npm run assistente -- migracao    roda um arquivo SQL no Supabase e publica
#   npm run assistente -- formulario  gera o segredo do Google Forms do Espaços de Leitura
#
# Valores secretos são digitados escondidos e nunca aparecem na tela.

cd "$(dirname "$0")/.."
ENV_FILE=".env.local"
PROJECT_REF="oktxtdzeetlxowizeewg"
SUPA="https://supabase.com/dashboard/project/$PROJECT_REF"
SITE="https://presente.presente.workers.dev"

# grava a mesma chave também no .dev.vars (usado pelo teste local da Cloudflare)
write_devvars() {
  local saved="$ENV_FILE"; ENV_FILE=".dev.vars"; write_env "$1" "$2"; ENV_FILE="$saved"
}

# cadastra um segredo na Cloudflare sem mostrar o valor
cf_secret() {
  if printf '%s' "$2" | npx --yes wrangler secret put "$1" >/dev/null 2>&1; then
    printf '  %s✓ cadastrado%s segredo %s na Cloudflare\n' "$GREEN" "$RESET" "$1"
  else
    SKIPPED+=("segredo $1 na Cloudflare: rode 'npx wrangler secret put $1' (e 'npx wrangler login' se pedir)")
    warn "não consegui cadastrar $1 na Cloudflare; veja o resumo no final"
    return 1
  fi
}

# o site publicado alcança o banco? (tenta por até ~40 s, tempo de a Cloudflare propagar)
site_ok() {
  local i code
  for i in 1 2 3 4 5 6 7 8; do
    code=$(curl -s -o /dev/null -w '%{http_code}' --ssl-no-revoke "$SITE/api/saude" 2>/dev/null || echo 000)
    [[ "$code" == "200" ]] && return 0
    sleep 5
  done
  return 1
}

# Publica seguindo os passos do AGENTS.md: testes, tipos, nenhuma lista aberta, publicar, conferir o site.
publish() {
  say "1/4 · Rodando os testes e a verificação de tipos..."
  if ! npm test --silent >/dev/null 2>&1 || ! npx tsc --noEmit >/dev/null 2>&1; then
    SKIPPED+=("publicação cancelada: 'npm test' ou 'npm run typecheck' falhou. Rode-os para ver o erro.")
    warn "testes ou verificação de tipos falharam: não publiquei."
    return 1
  fi
  say "2/4 · Conferindo se alguma lista está recebendo assinaturas..."
  local abertas
  if ! abertas=$(node --no-warnings scripts/listas-abertas.mjs 2>&1); then
    printf '%s\n' "$abertas" | sed 's/^/    /'
    warn "um voluntário com o formulário aberto pode perder o envio durante a troca de versão."
    if ! confirm "Publicar mesmo assim?"; then
      SKIPPED+=("publicação adiada: há lista recebendo assinaturas; rode de novo depois do encontro")
      return 1
    fi
  fi
  say "3/4 · Compilando e publicando (leva cerca de 1 minuto)..."
  if ! { npx opennextjs-cloudflare build >/dev/null 2>&1 && npx wrangler deploy >/dev/null 2>&1; }; then
    SKIPPED+=("publicação: rode 'npx opennextjs-cloudflare build && npx wrangler deploy' para ver o erro")
    warn "a publicação falhou; o site continua na versão anterior."
    return 1
  fi
  say "4/4 · Conferindo o site publicado..."
  if site_ok; then
    printf '  %s✓ publicado e funcionando%s em %s\n' "$GREEN" "$RESET" "$SITE"
  else
    SKIPPED+=("o site não respondeu depois de publicar: para voltar à versão anterior rode 'npx wrangler rollback'")
    warn "o site não respondeu. Veja o resumo no final (dá para voltar à versão anterior)."
    return 1
  fi
}

TASK="${1:-}"
case "$TASK" in

# ── 1. Trocar a chave secreta do Supabase ─────────────────────────────────
chave)
  TOTAL_STAGES=4
  banner "Presente · trocar a chave secreta do Supabase"
  CHAVE_ANTIGA=$(_existing SUPABASE_SECRET_KEY || true)
  NUVEM_OK=0; LOCAL_OK=0; SITE_OK=0

  stage "Criar a nova chave secreta"
  say "Primeiro criamos a chave nova; a antiga só é apagada no fim, e só se tudo funcionar."
  open_url "$SUPA/settings/api-keys"
  step "Na seção 'Secret keys', clique em '+ New secret key' (ou 'Add new secret key')."
  step "Dê o nome 'presente_$(date +%Y%m)' (só minúsculas, números e _) e confirme."
  step "Clique no ícone de copiar da chave NOVA (começa com sb_secret_)."
  while :; do
    ask_secret SUPABASE_SECRET_KEY "Cole a chave NOVA (fica escondida):"
    if [[ "$SUPABASE_SECRET_KEY" != sb_secret_* ]]; then
      # diz o motivo sem mostrar a chave
      if [[ -z "$SUPABASE_SECRET_KEY" ]]; then warn "não chegou nada: a colagem não funcionou neste terminal. Tente Shift+Insert ou o clique direito."
      elif [[ "$SUPABASE_SECRET_KEY" == sb_publishable_* ]]; then warn "essa é a chave PÚBLICA (sb_publishable_). Copie a da seção 'Secret keys'."
      elif [[ "$SUPABASE_SECRET_KEY" == *[•*…]* ]]; then warn "a chave veio mascarada (com •••). Use o ícone de copiar da chave, não selecione o texto."
      else warn "chegou um texto de ${#SUPABASE_SECRET_KEY} caracteres que não começa com sb_secret_ (começa com '${SUPABASE_SECRET_KEY:0:3}'). Copie de novo pelo ícone da chave."
      fi
    elif [[ "$SUPABASE_SECRET_KEY" == "$CHAVE_ANTIGA" ]]; then
      warn "essa é a chave ANTIGA (ou você apertou Enter sem colar). Cole a chave nova."
    else
      break
    fi
  done
  write_env SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
  write_devvars SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY"
  pause "Enter para continuar"

  stage "Enviar a chave nova para o site"
  say "O site publicado usa a chave guardada como segredo na Cloudflare."
  if confirm "Atualizar o segredo SUPABASE_SECRET_KEY na Cloudflare agora?"; then
    cf_secret SUPABASE_SECRET_KEY "$SUPABASE_SECRET_KEY" && NUVEM_OK=1
  else
    SKIPPED+=("segredo SUPABASE_SECRET_KEY na Cloudflare (npx wrangler secret put SUPABASE_SECRET_KEY)")
  fi
  pause "Enter para continuar"

  stage "Testar a chave nova"
  say "Neste computador..."
  if npm run --silent check >/dev/null 2>&1; then LOCAL_OK=1; printf '  %s✓ a chave nova funciona aqui%s\n' "$GREEN" "$RESET"
  else warn "a chave nova não funcionou aqui (rode 'npm run check' para ver o motivo)."; fi
  if (( NUVEM_OK )); then
    say "No site publicado..."
    if site_ok; then SITE_OK=1; printf '  %s✓ o site publicado acessa o banco com a chave nova%s\n' "$GREEN" "$RESET"
    else warn "o site publicado não respondeu com a chave nova."; fi
  fi
  pause "Enter para continuar"

  stage "Revogar a chave antiga"
  if (( LOCAL_OK && SITE_OK )); then
    open_url "$SUPA/settings/api-keys"
    step "Na seção 'Secret keys', encontre a chave ANTIGA (não a 'presente_$(date +%Y%m)')."
    step "Clique nos três pontinhos dela e escolha 'Delete' (ou 'Revoke'); confirme."
    pause "Enter quando a chave antiga estiver apagada"
  else
    warn "NÃO apague a chave antiga: a nova ainda não está funcionando em todos os lugares."
    note "O site continua funcionando com a chave antiga enquanto ela existir."
    SKIPPED+=("revogar a chave antiga: só depois que 'npm run check' e $SITE/api/saude estiverem ok (rode 'npm run assistente -- chave' de novo)")
    pause "Enter para ver o resumo"
  fi
  finish
  ;;

# ── 2. Ativar a verificação "não sou robô" (Turnstile) ───────────────────
turnstile)
  TOTAL_STAGES=3
  banner "Presente · ativar a verificação anti-robô (Turnstile)"

  stage "Criar o widget na Cloudflare"
  open_url "https://dash.cloudflare.com/?to=/:account/turnstile"
  step "Clique em 'Add widget'."
  step "Nome: Presente.  Hostname: presente.presente.workers.dev (clique em 'Add')."
  step "Widget Mode: 'Managed'.  Pre-clearance: 'No'.  Clique em 'Create'."
  step "A tela seguinte mostra a 'Site Key' e a 'Secret Key'."
  ask NEXT_PUBLIC_TURNSTILE_SITE_KEY "Cole a Site Key (é pública):"
  write_env NEXT_PUBLIC_TURNSTILE_SITE_KEY "$NEXT_PUBLIC_TURNSTILE_SITE_KEY"
  ask_secret TURNSTILE_SECRET_KEY "Cole a Secret Key (fica escondida):"
  cf_secret TURNSTILE_SECRET_KEY "$TURNSTILE_SECRET_KEY" || true
  note "A Secret Key não é gravada neste computador: só o site publicado precisa dela."
  pause "Enter para continuar"

  stage "Publicar o site com a verificação"
  say "A Site Key entra no site na hora da compilação, por isso publicamos de novo."
  if confirm "Publicar agora?"; then publish || true; else SKIPPED+=("publicar o site (npx opennextjs-cloudflare build && npx wrangler deploy)"); fi
  pause "Enter para continuar"

  stage "Testar no celular"
  step "No celular, abra o link de uma lista que esteja aberta (ou abra uma pelo painel)."
  step "Assine como teste: o envio deve funcionar normalmente (a verificação quase sempre é invisível)."
  step "Depois, remova a presença de teste pelo painel."
  pause "Enter quando tiver testado"
  finish
  ;;

# ── 3. Dar acesso a uma nova pessoa da Equipe ────────────────────────────
equipe)
  TOTAL_STAGES=3
  banner "Presente · nova pessoa da Equipe"

  stage "Nome e usuário"
  say "A pessoa vai entrar digitando só o usuário (ex.: maria)."
  printf '  %sNome (como aparece no painel):%s ' "$BOLD" "$RESET"; read -r NOME || true
  printf '  %sUsuário (sem espaços nem acentos, ex.: maria):%s ' "$BOLD" "$RESET"; read -r USUARIO || true
  USUARIO=$(printf '%s' "$USUARIO" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9._-')
  if [[ -z "$USUARIO" || -z "$NOME" ]]; then warn "nome e usuário são obrigatórios"; exit 1; fi
  EMAIL="$USUARIO@presente.app"
  say "Login: $USUARIO   (conta interna: $EMAIL)"
  pause "Enter para continuar"

  stage "Criar a conta no Supabase"
  open_url "$SUPA/auth/users"
  step "Clique em 'Add user' e depois em 'Create new user'."
  step "Email: $EMAIL"
  step "Password: uma senha forte (mínimo 10 caracteres). Passe à pessoa por um canal privado."
  step "Deixe marcado 'Auto Confirm User' e clique em 'Create user'."
  pause "Enter quando a conta estiver criada"

  stage "Liberar o acesso ao painel"
  say "Adicionando $EMAIL à equipe autorizada..."
  if EMAIL="$EMAIL" NOME="$NOME" node scripts/add-staff.mjs; then
    printf '  %s✓ %s liberado(a)%s (login: %s)\n' "$GREEN" "$NOME" "$RESET" "$USUARIO"
  else
    SKIPPED+=("liberar $EMAIL: no SQL Editor rode  insert into public.staff (email, name) values ('$EMAIL', '$NOME');")
  fi
  pause "Enter para ver o resumo"
  finish
  ;;

# ── 4. Rodar uma migração SQL e publicar ────────────────────────────────
migracao)
  TOTAL_STAGES=3
  banner "Presente · migração do banco + publicação"

  stage "Escolher o arquivo"
  say "Migrações disponíveis:"
  ls -1 supabase/migrations/ | sed 's/^/    /'
  printf '  %sNome do arquivo a rodar:%s ' "$BOLD" "$RESET"; read -r ARQ || true
  ARQ="supabase/migrations/${ARQ##*/}"
  if [[ ! -f "$ARQ" ]]; then warn "arquivo não encontrado: $ARQ"; exit 1; fi
  if command -v clip.exe >/dev/null 2>&1; then
    clip.exe < "$ARQ"
    say "✓ conteúdo de $ARQ copiado para a área de transferência."
  else
    say "Abra $ARQ e copie todo o conteúdo."
  fi
  pause "Enter para continuar"

  stage "Rodar no Supabase"
  warn "A migração vem ANTES de publicar o código que depende dela."
  open_url "$SUPA/sql/new"
  step "Cole (Ctrl+V) no editor e clique em 'Run'."
  step "Deve aparecer 'Success'. Se aparecer erro, pare aqui e peça ajuda."
  if ! confirm "A migração rodou com sucesso?"; then warn "Parando sem publicar."; exit 1; fi

  stage "Publicar o código novo"
  if confirm "Publicar agora?"; then publish || true; else SKIPPED+=("publicar o site (npx opennextjs-cloudflare build && npx wrangler deploy)"); fi
  pause "Enter para ver o resumo"
  finish
  ;;

# ── 5. Segredo do Google Forms do Espaços de Leitura ─────────────────────
formulario)
  TOTAL_STAGES=2
  banner "Presente · segredo do Google Forms (Espaços de Leitura)"

  stage "Gerar e guardar o segredo"
  say "O script do Google Forms só consegue mandar respostas para a Central com este segredo."
  if [[ -n "$(_existing FORMS_SECRET || true)" ]] && ! confirm "Já existe um segredo. Gerar um NOVO (o antigo para de funcionar)?"; then
    FORMS_SECRET=$(_existing FORMS_SECRET)
  else
    FORMS_SECRET=$(node -e "console.log(require('crypto').randomBytes(24).toString('base64url'))")
    write_env FORMS_SECRET "$FORMS_SECRET"
    write_devvars FORMS_SECRET "$FORMS_SECRET"
    cf_secret FORMS_SECRET "$FORMS_SECRET" || true
  fi
  pause "Enter para ver o segredo que vai para o Forms"

  stage "Passar o segredo para quem é dona do Forms"
  say "Copie o segredo abaixo e envie por um canal privado (não em grupo):"
  printf '\n      %s%s%s\n\n' "$BOLD" "$FORMS_SECRET" "$RESET"
  step "No Apps Script do Forms: Configurações do projeto (engrenagem) → Propriedades do script."
  step "Adicionar propriedade:  SEGREDO_CENTRAL  =  (o segredo acima)."
  note "Passo a passo completo: scripts/google-forms/COMO-INSTALAR.md"
  pause "Enter quando tiver copiado (a tela será limpa)"
  finish
  ;;

*)
  printf '\nUso: npm run assistente -- <tarefa>\n\n'
  printf '  chave       troca a chave secreta do Supabase\n'
  printf '  turnstile   ativa a verificação "não sou robô"\n'
  printf '  equipe      dá acesso a uma nova pessoa da Equipe\n'
  printf '  migracao    roda um arquivo SQL no Supabase e publica\n'
  printf '  formulario  gera o segredo do Google Forms do Espaços de Leitura\n\n'
  exit 1
  ;;
esac
